namespace XlibraryPro.Domain.Common;

/// <summary>
/// Base entity for all domain entities.
/// IDs follow the YYYYMMDD+8digit format generated by the DB generate_id() function.
/// </summary>
public abstract class BaseEntity
{
    public long Id { get; protected set; }

    protected BaseEntity() { }
    protected BaseEntity(long id) => Id = id;

    public override bool Equals(object? obj)
    {
        if (obj is not BaseEntity other) return false;
        if (ReferenceEquals(this, other)) return true;
        if (GetType() != other.GetType()) return false;
        return Id == other.Id;
    }

    public override int GetHashCode() => Id.GetHashCode();

    public static bool operator ==(BaseEntity? a, BaseEntity? b)
    {
        if (a is null && b is null) return true;
        if (a is null || b is null) return false;
        return a.Equals(b);
    }

    public static bool operator !=(BaseEntity? a, BaseEntity? b) => !(a == b);
}